### ISSUE TITLE
YAMLException: Specified list of YAML types (or a single Type object) contains a non-Type object

### ISSUE THREAD

**Issue by jiangtj** [nodeca/js-yaml-js-types#2]
I encountered a YAMLException problem

```
ERROR {
  err: YAMLException: Specified list of YAML types (or a single Type object) contains a non-Type object.
      at C:\Users\MrTT\Desktop\test112\node_modules\@jiangtj\hexo-next-pwa\node_modules\js-yaml\lib\schema.js:104:13
      at Array.forEach (<anonymous>)
      at Schema.extend (C:\Users\MrTT\Desktop\test112\node_modules\@jiangtj\hexo-next-pwa\node_modules\js-yaml\lib\schema.js:102:12)
      at C:\Users\MrTT\Desktop\test112\node_modules\@jiangtj\hexo-next-pwa\index.js:13:36
      at C:\Users\MrTT\Desktop\test112\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\MrTT\Desktop\test112\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    reason: 'Specified list of YAML types (or a single Type object) contains a non-Type object.',
    mark: undefined
  }
}
```

But it’s strange that the code I introduced is the same as the example

In my code `index.js:13:36`

![image](https://user-images.githubusercontent.com/15902347/106569212-37fc7800-656f-11eb-8b7a-8f85820e7f03.png)

Reproduction

```
yarn global add hexo
hexo init adir
cd adir
yarn add @jiangtj/hexo-next-pwa@beta
hexo g
```

**Comment by jiangtj** [comment]
The version of `js-yaml` used by `hexo` is `3.12`, will it make a difference?

**Comment by puzrin** [comment]
You need v4.+

See https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md & changelog

**Comment by jiangtj** [comment]
In my project it is already 4.0, but some dependencies are 3.12

**Comment by puzrin** [comment]
You could start with minimal setup - install yaml 4 & this package only, and do as suggested in readme https://github.com/nodeca/js-yaml-js-types#usage.

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/106580993-536e7f80-657d-11eb-8932-6767f63777fb.png)
![image](https://user-images.githubusercontent.com/15902347/106581008-58cbca00-657d-11eb-8ceb-710e175674b4.png)
![image](https://user-images.githubusercontent.com/15902347/106581038-61240500-657d-11eb-9086-6fb983ce8b4c.png)

In fact, it is good in my project. But it as a dependency in other projects, it will report errors. So I doubt if the external dependency `js-yaml:3.12` affects it?

As a plug-in developer, I can only guarantee that my project has been upgraded to `4.0`, but if `js-yaml` requires all dependencies to be upgraded to `4.0` to use, then I can only choose to return. Because this upgrade is time-consuming.

**Comment by puzrin** [comment]
If `package.json` requires `js-yaml` 4 and `js-yaml-js-types`, this should work.

Node allows different versions in different packages. This is documented, and i don't know what i can describe better.

**Comment by RonaldJerez** [comment]
Not sure why this was closed unfixed, but this is still an issue.  If you use js-yaml version > 4 and this in the same project it works fine, but once you use that project as a dependency in a different project you get this error because it is not the same instance. 

Additionally if you try to extend one of the existing tags, and a different version of js-yaml gets hoisted, then it fails. For example:

```js
const jsTypes = require('js-yaml-js-types')

const mockRegExpOptions = {
  ...jsTypes.regexp.options,
  instanceOf: types.CustomRegExp,
  construct: (data) => {
    const regexp = jsTypes.regexp.construct(data)
    return new types.CustomRegExp(regexp)
  }
}

const RegExp__string = new yaml.Type('!regexp', mockRegExpOptions)
```

The above code works fine in my project, but once I include this project as a dependency I was getting an error that `.options` did that existing in regexp.

The solution is to move js-yaml to peer dependency, this guarantees the right version and the same instance.
